cdata =
{
	A4E_AIRCRAFTNAME                  = _('A-4E-C'),
	TRIMSPEEDL                        = _('Trim Speed'),
	A4E_CATLAUNCHMODE_LABEL           = _('Catapult Launch Mode'),
	A4E_CATLAUNCHMODE_HELP            = _('Launch the catapult when throttle at MIL POWER.'),
	A4E_CATLAUNCHMODE_HELP2           = _('Launch the catapult with the Pilot Salute command'),
	A4E_CATAPULT_ALIGNMENT_CHECK_TEXT = _('Bypass Catapult Alignment Check'),
	A4E_CATAPULT_ALIGNMENT_CHECK_HELP = _('Check if aircraft is aligned with a catapult before allowing catapult hook up.'),
	A4E_EXPERIMENTAL_EFM_CHECK_TEXT	  = _('Enable the experimental EFM'),
	A4E_EXPERIMENTAL_EFM_CHECK_HELP   = _('Should the A-4E-C use the experimental external flight model or the simple flight model.'),
	A4E_COCKPIT_SHAKE_SLIDER_TEXT 	  = _('Cockpit Shake'),
	A4E_COCKPIT_SHAKE_SLIDER_HELP	  = _('Defines the amount of cockpit shaking experienced due to load on the aircraft.'),
	A4E_COCKPIT_CSS_TEXT			  = _('FFB CSS Mode Deflection'),
	A4E_COCKPIT_CSS_HELP			  = _('Defines % of stick deflection at which AFCS switches to Control Stick Steering (FFB sticks only).'),
	A4E_WHEEL_BRAKE_ASSIST_CHECK_LABEL = _('Simple Braking (Rudder-Assisted)'),
	A4E_WHEEL_BRAKE_ASSIST_CHECK_TOOLTIP = _('Simple Braking Enabled'),
	A4E_WHEEL_BRAKE_ASSIST_CHECK_HELP  = _('When enabled, the Wheel Brake binding applies to the Left and Right Wheelbrakes in proportion to current rudder input.'),
	A4E_OLD_RADAR_CHECK_LABEL = _('AN/APG-53A Radar Legacy Mode'),
	A4E_OLD_RADAR_CHECK_TOOLTIP = _('Enable this option if you are having performance issues in the cockpit.'),
}
